#!/usr/bin/env bash
#
# Copyright (C) Bruno Félix Rezende Ribeiro <oitofelix@gnu.org>
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

set -o errexit -o pipefail

function usage
{
    echo "Usage: $(basename $0) BKP_USER BKP_HOST BKP_ARCHIVE

Verify integrity of Tar-archived, Gzip-compressed and GPG-encrypted
BKP_ARCHIVE within BKP_HOST as BKP_USER.

Decryption, decompression and archive verification are all performed
on the local host.

Hint: BKP_HOST may be localhost." 1>&2
}

trap usage EXIT

: ${1:?BKP_USER argument not given}
: ${2:?BKP_HOST argument not given}
: ${3:?BKP_ARCHIVE argument not given}

trap EXIT

bkp_user=$1
bkp_host=$2
bkp_archive=$3

ssh "$bkp_user@$bkp_host" \
    cat "$bkp_archive" |
    gpg --decrypt \
        --quiet |
    gunzip |
    tar vvt
