#!/usr/bin/env bash
#
# Copyright (C) Bruno Félix Rezende Ribeiro <oitofelix@gnu.org>
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

set -o errexit -o pipefail

function usage
{
    echo "Usage: $(basename $0) BKP_USER BKP_HOST BKP_ARCHIVE BKP_PATH RST_USER RST_HOST RST_PATH

Restore BKP_PATH residing within Tar-archived, Gzip-compressed and
GPG-encrypted BKP_ARCHIVE stored in BKP_HOST as BKP_USER to RST_PATH
within RST_HOST as RST_USER.

Tar is used on RST_HOST to extract the backup archive sent to it
through SSH.  Decryption and decompression are performed on the local
host.

Hint: BKP_HOST and/or RST_HOST may be the same host and/or localhost." 1>&2
}

trap usage EXIT

: ${1:?BKP_USER argument not given}
: ${2:?BKP_HOST argument not given}
: ${3:?BKP_ARCHIVE argument not given}
: ${4:?BKP_PATH argument not given}
: ${5:?RST_USER argument not given}
: ${6:?RST_HOST argument not given}
: ${7:?RST_PATH argument not given}

trap EXIT

bkp_user=$1
bkp_host=$2
bkp_archive=$3
bkp_path=$4
rst_user=$5
rst_host=$6
rst_path=$7

ssh "$bkp_user@$bkp_host" \
    "$(printf 'cat %q' \
              "$bkp_archive")" |
    gpg --decrypt \
        --quiet |
    gunzip |
    ssh "$rst_user@$rst_host" \
        "$(printf 'tar vvxf - -C %q %q' \
                  "$rst_path" \
                  "$bkp_path")"
