#!/usr/bin/env bash
#
# Copyright (C) Bruno Félix Rezende Ribeiro <oitofelix@gnu.org>
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

set -o errexit -o pipefail

function usage
{
    echo "Usage: $(basename $0) SRC_USER SRC_HOST SRC_PATH BKP_USER BKP_HOST BKP_ARCHIVE

Backup SRC_PATH from SRC_HOST as SRC_USER into Tar-archived,
Gzip-compressed and GPG-encrypted BKP_ARCHIVE within BKP_HOST as
BKP_USER.

Tar is used on SRC_HOST to archive the backup before sending it
through SSH to BKP_HOST.  Compression and encryption are performed on
the local host.

Hint: SRC_HOST and/or BKP_HOST may be the same host and/or localhost." 1>&2
}

trap usage EXIT

: ${1:?SRC_USER argument not given}
: ${2:?SRC_HOST argument not given}
: ${3:?SRC_PATH argument not given}
: ${4:?BKP_USER argument not given}
: ${5:?BKP_HOST argument not given}
: ${6:?BKP_ARCHIVE argument not given}

trap EXIT

src_user=$1
src_host=$2
src_path=$3
bkp_user=$4
bkp_host=$5
bkp_archive=$6

ssh "$src_user@$src_host" \
    tar vvcf - \
    "$src_path" |
    gzip |
    gpg --symmetric \
	      --quiet |
    ssh "$bkp_user@$bkp_host" \
        tee "$bkp_archive" > /dev/null
